---
title: Code For Dayton
timezone: UTC
markdown: kramdown
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  rooms:
    title: Rooms
    output: true
email: team@codefordayton.org
description:
  'Part of the Alliance of Civic Technologists (ACT) network, we are a volunteer group
  of developers, designers, data geeks, and citizen activists who use creative technology
  to solve civic and social problems.'
baseurl: ''
url: https://www.codefordayton.org
author: Dave Best
defaults:
  - scope:
      type: posts
    values:
      layout: post
# NOTE:If you change the below donate_url you should also update the URL here: https://github.com/codefordayton/.github/FUNDING.yml
donate_url: https://hcb.hackclub.com/donations/start/code-for-dayton
twitter_url: https://twitter.com/codefordayton
github_url: https://github.com/codefordayton
meetup_url: https://www.meetup.com/gem-city-tech/
privacy_policy_url: https://www.codefordayton.org/privacy-policy/
discord_url: https://discord.gg/3CUaY5DEwr
facebook_url: https://www.facebook.com/Code-For-Dayton-1501498193512256

plugins:
  - jekyll-redirect-from
  - jekyll-feed
